version: '2'
services:
  mannenweekend-mysql:
    image: mysql:latest
    environment:
      - MYSQL_USER=mannenweekend
      - MYSQL_ROOT_PASSWORD=mannenweekend
      - MYSQL_PASSWORD=mannenweekend
      - MYSQL_DATABASE=mannenweekend
    ports:
      - 3306:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
